# Generated by Django 4.0.2 on 2022-03-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subject_add',
        ),
    ]
